# 1. Importo Librerías

In [1]:
import pandas as pd
import numpy as np
import re

# Importing the cleaning functions:
import sys
sys.path.append("../")
import src.cleaning_functions as cf

# 2. Cargo Datos

# 3. EDA

In [2]:
datos_1d = pd.read_csv("../data/datos_1_dorm.csv")

In [3]:
datos_4h = pd.read_csv("../data/datos_4_h_m_v_s.csv")

In [4]:
datos_ana = pd.read_csv("../data/datos_4_h_v_s.csv")

In [5]:
datos_4h_val = datos_ana[:300]

In [6]:
df = pd.concat([datos_1d, datos_4h, datos_4h_val ], axis=0)

In [7]:
df

titulo  \
0          Alojamiento entero: piso. Anfitrión: Javier   
1         Alojamiento entero: piso. Anfitrión: Melissa   
2          Alojamiento entero: piso. Anfitrión: Javier   
3    Alojamiento entero: piso. Anfitrión: Julio Víctor   
4    Alojamiento entero: piso. Anfitrión: Airbnbleg...   
..                                                 ...   
295                                                NaN   
296                                                NaN   
297                                                NaN   
298                                                NaN   
299                                                NaN   

                                              all_info  \
0        2 huéspedes · 1 dormitorio · 2 camas · 1 baño   
1         2 huéspedes · 1 dormitorio · 1 cama · 1 baño   
2        2 huéspedes · 1 dormitorio · 2 camas · 1 baño   
3       5 huéspedes · 2 dormitorios · 3 camas · 1 baño   
4        4 huéspedes · 1 dormitorio · 2 camas · 1 baño   
..                                                 ...   
295    8 huéspedes · 3 dormitorios · 4 camas · 2 baños   
296      5 huéspedes · 1 dormitorio · 3 camas · 1 baño   
297  7 huéspedes · 4 dormitorios · 7 camas · 1,5 baños   
298    5 huéspedes · 3 dormitorios · 6 camas · 2 baños   
299     6 huéspedes · 2 dormitorios · 3 camas · 1 baño   

                                       características  \
0    Alojamiento entero\n(apartamento): será solo p...   
1    Alojamiento entero\n(apartamento): será solo p...   
2    Alojamiento entero\n(apartamento): será solo p...   
3    Alojamiento entero\n(apartamento): será solo p...   
4    Alojamiento entero\n(apartamento): será solo p...   
..                                                 ...   
295  Alojamiento entero\n(apartamento): será solo p...   
296  Alojamiento entero\n(apartamento): será solo p...   
297  Alojamiento entero\n(apartamento): será solo p...   
298  Alojamiento entero\n(apartamento): será solo p...   
299  Alojamiento entero\n(apartamento): será solo p...   

                                                precio  \
0    55€\n / noche\n55€ por noche\n4,90\n(415 evalu...   
1    60€\n / noche\n60€ por noche\n4,80\n(5 evaluac...   
2    55€\n / noche\n55€ por noche\n4,93\n(46 evalua...   
3    85€\n / noche\n85€ por noche\n4,95\n(459 evalu...   
4    60€\n / noche\n60€ por noche\n3,33\n(3 evaluac...   
..                                                 ...   
295  228€\n / noche\n228€ por noche\n4,91\n(11 eval...   
296  93€\n / noche\n93€ por noche\n3,50\n(8 evaluac...   
297  160€\n / noche\n160€ por noche\n4,85\n(89 eval...   
298  125€\n / noche\n125€ por noche\n5,0\n(6 evalua...   
299  121€\n / noche\n121€ por noche\n4,69\n(26 eval...   

                                                  usos  
0    ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...  
1    2 noches en Madrid\n19 de ago. de 2022 - 21 de...  
2    ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...  
3    ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...  
4    ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...  
..                                                 ...  
295  ¿Dónde dormirás?\n1 de 2 páginas\n1 / 2\nDormi...  
296  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...  
297  2 noches en València\n1 de jul. de 2022 - 3 de...  
298  ¿Qué hay en este alojamiento?\nVistas al perfi...  
299  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...  

[2400 rows x 5 columns]

In [8]:
ciudad = pd.read_csv("../data/ciudades.csv")

In [9]:
ciudad

ciudad
0      Madrid
1      Madrid
2      Madrid
3      Madrid
4      Madrid
...       ...
2395  Sevilla
2396  Sevilla
2397  Sevilla
2398  Sevilla
2399  Sevilla

[2400 rows x 1 columns]

In [10]:
urls = pd.read_csv("../data/datos_URLS.csv")

In [11]:
urls.columns = ["urls"]

In [12]:
urls

urls
0     https://www.airbnb.es/rooms/20814468?adults=1&...
1     https://www.airbnb.es/rooms/18565479?adults=1&...
2     https://www.airbnb.es/rooms/46724279?adults=1&...
3     https://www.airbnb.es/rooms/18093383?adults=1&...
4     https://www.airbnb.es/rooms/47445221?adults=1&...
...                                                 ...
2395  https://www.airbnb.es/rooms/50419829?adults=5&...
2396  https://www.airbnb.es/rooms/40064538?adults=5&...
2397  https://www.airbnb.es/rooms/16674353?adults=5&...
2398  https://www.airbnb.es/rooms/13621279?adults=5&...
2399  https://www.airbnb.es/rooms/23816021?adults=5&...

[2400 rows x 1 columns]

In [13]:
nombres = pd.read_csv("../data/datos_NOMBRES.csv")

In [14]:
nombres

nombre
0              *Studio Centre-Live-In Atocha-WiFi,A/C *
1                PISO MODERNO EN PLENO CENTRO DE MADRID
2           <<<Studio Centre-Live-In-Atocha-WIFI,A/C>>>
3                 Mi rincón de Goya (My corner in Goya)
4                                           No hay dato
...                                                 ...
2395  ◤ Apartamento a estrenar con estilo con camas ...
2396       Coroa del Mar. Apartamento Duplex 5 pax+WIFI
2397      Amazing Apartment ONLY LONG STAY center town.
2398                Luminoso y con encantadora terraza.
2399  ApartUP Ruzafa Central Park. WiFi + AACC + BALCÓN

[2400 rows x 1 columns]

In [15]:
df_ = pd.merge(df, nombres, left_index = True, right_index = True)

In [16]:
df__ = pd.merge(df_, ciudad, left_index = True, right_index = True)

In [17]:
datos = pd.merge(df__, urls, left_index = True, right_index = True)

In [18]:
datos

titulo  \
0           Alojamiento entero: piso. Anfitrión: Javier   
0                                                   NaN   
0                                                   NaN   
1          Alojamiento entero: piso. Anfitrión: Melissa   
1                                                   NaN   
...                                                 ...   
1195  Alojamiento entero: piso. Anfitrión: Inmoprill...   
1196        Alojamiento entero: piso. Anfitrión: Manuel   
1197      Alojamiento entero: loft. Anfitrión: Macarena   
1198       Alojamiento entero: piso. Anfitrión: Ignacio   
1199          Alojamiento entero: piso. Anfitrión: Luis   

                                             all_info  \
0       2 huéspedes · 1 dormitorio · 2 camas · 1 baño   
0     6 huéspedes · 3 dormitorios · 4 camas · 2 baños   
0      5 huéspedes · 2 dormitorios · 4 camas · 1 baño   
1        2 huéspedes · 1 dormitorio · 1 cama · 1 baño   
1      5 huéspedes · 3 dormitorios · 3 camas · 1 baño   
...                                               ...   
1195    4 huéspedes · 1 dormitorio · 2 camas · 1 baño   
1196     2 huéspedes · 1 dormitorio · 1 cama · 1 baño   
1197          4 huéspedes · Estudio · 1 cama · 1 baño   
1198          2 huéspedes · Estudio · 1 cama · 1 baño   
1199    3 huéspedes · 1 dormitorio · 2 camas · 1 baño   

                                        características  \
0     Alojamiento entero\n(apartamento): será solo p...   
0     Alojamiento entero\n(apartamento): será solo p...   
0     Alojamiento entero\n(apartamento): será solo p...   
1     Alojamiento entero\n(apartamento): será solo p...   
1     Alojamiento entero\n(apartamento): será solo p...   
...                                                 ...   
1195  Alojamiento entero\n(apartamento): será solo p...   
1196  Alojamiento entero\n(apartamento): será solo p...   
1197  Alojamiento entero\n(loft): será solo para ti....   
1198  Alojamiento entero\n(apartamento): será solo p...   
1199  Alojamiento entero\n(apartamento): será solo p...   

                                                 precio  \
0     55€\n / noche\n55€ por noche\n4,90\n(415 evalu...   
0     99€\n / noche\n99€ por noche\n4,40\n(20 evalua...   
0     83€\n / noche\n83€ por noche\n4,52\n(31 evalua...   
1     60€\n / noche\n60€ por noche\n4,80\n(5 evaluac...   
1     50€\n / noche\n50€ por noche\n4,84\n(25 evalua...   
...                                                 ...   
1195  75€\n / noche\n75€ por noche\n4,50\n(36 evalua...   
1196  51€\n / noche\n51€ por noche\n4,86\n(44 evalua...   
1197  59€\n / noche\n59€ por noche\n4,50\n(181 evalu...   
1198  70€\n / noche\n70€ por noche\n4,65\n(75 evalua...   
1199  55€\n / noche\n55€ por noche\n4,80\n(64 evalua...   

                                                   usos  \
0     ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...   
0     ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...   
0     2 noches en Valencia / València\n25 de mar. de...   
1     2 noches en Madrid\n19 de ago. de 2022 - 21 de...   
1     ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...   
...                                                 ...   
1195  ¿Qué hay en este alojamiento?\nWifi\nAire acon...   
1196  ¿Qué hay en este alojamiento?\nWifi\nAparcamie...   
1197  ¿Qué hay en este alojamiento?\nCocina\nWifi\nP...   
1198  ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...   
1199  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...   

                                               nombre   ciudad  \
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   Madrid   
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   Madrid   
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   Madrid   
1              PISO MODERNO EN PLENO CENTRO DE MADRID   Madrid   
1              PISO MODERNO EN PLENO CENTRO DE MADRID   Madrid   
...                                               ...      ...   
1195                               BELLA VISTA MODERN  Sevilla   


# 4. Limpieza Datos:

## ALL_INFO

In [19]:
datos["all_info"] = datos["all_info"].apply(cf.splity_info)

In [20]:
datos[["huespedes", "dormitorios", "camas", "baños"]] = datos["all_info"].apply(pd.Series)

### Huéspedes

In [21]:
datos["huespedes"].unique()

array(['2 huéspedes ', '6 huéspedes ', '5 huéspedes ', '4 huéspedes ',
       '7 huéspedes ', '1 huésped ', '8 huéspedes ', '3 huéspedes ',
       'No hay dato', '10 huéspedes ', '12 huéspedes ', '9 huéspedes '],
      dtype=object)

In [22]:
datos["huespedes"] = datos["huespedes"].apply(cf.get_info)

In [23]:
datos["huespedes"].unique()

array([ 2,  6,  5,  4,  7,  1,  8,  3,  0, 10, 12,  9])

In [24]:
datos["huespedes"] = datos["huespedes"].replace(0, datos["huespedes"].mode()[0])

In [25]:
datos["huespedes"].unique()

array([ 2,  6,  5,  4,  7,  1,  8,  3, 10, 12,  9])

In [26]:
datos["huespedes"].value_counts()

6     666
2     593
5     417
4     252
1     154
3     113
8      97
7      85
10     12
9       9
12      2
Name: huespedes, dtype: int64

### Dormitorios

In [27]:
datos["dormitorios"] = datos["dormitorios"].apply(cf.get_info)

In [28]:
datos["dormitorios"].unique()

array([1, 3, 2, 4, 0, 5, 6])

In [29]:
datos["dormitorios"].value_counts()

1    938
2    718
3    531
0    140
4     66
5      6
6      1
Name: dormitorios, dtype: int64

### Camas

In [30]:
datos["camas"].unique()

array([' 2 camas ', ' 4 camas ', ' 1 cama ', ' 3 camas ', ' 5 camas ',
       ' 6 camas ', ' 1 baño', ' 10 camas ', ' 1 baño compartido',
       ' 4 baños compartidos', nan, ' 7 camas ', ' 1,5 baños',
       ' 9 camas ', ' 8 camas ', ' 2 baños', ' 3 camas', ' 5 camas',
       ' 11 camas ', ' 1,5 baños compartidos', ' 1 baño privado',
       ' 2,5 baños', ' 2 baños compartidos', ' 3 baños'], dtype=object)

In [31]:
datos["camas"] = datos["camas"].apply(cf.info_camas)

In [32]:
datos["camas"].fillna(int(datos["camas"].mode()), inplace=True)

In [33]:
datos["camas"] = datos["camas"].apply(cf.get_integrer)

In [34]:
datos["camas"].unique()

array([2, 4, 1, 3, 5, 6, 7, 9, 8])

In [35]:
datos["camas"].value_counts()

1    753
3    451
4    440
2    416
5    202
6     90
7     36
8      7
9      5
Name: camas, dtype: int64

### Baños

In [36]:
datos["baños"].unique()

array([' 1 baño', ' 2 baños', ' 1,5 baños', ' 1 baño compartido',
       ' 2,5 baños', nan, ' 3 baños', ' 1 baño privado',
       ' 4 baños compartidos', ' 2,5 baños compartidos',
       ' 3 baños compartidos', ' 2 baños compartidos',
       ' 1,5 baños compartidos', ' 4 baños', ' 0 baños compartidos',
       ' 4,5 baños', ' 3,5 baños'], dtype=object)

In [37]:
datos["baños"] = datos["baños"].apply(cf.info_baños)

In [38]:
datos["baños"].fillna(int(datos["baños"].mode()), inplace=True)

In [39]:
datos["baños"] = datos["baños"].apply(cf.get_integrer)

In [40]:
datos["baños"] = datos["baños"].replace(0, datos["baños"].mode()[0])

In [41]:
datos["baños"].unique()

array([1, 2, 3, 4])

In [42]:
datos["baños"].value_counts()

1    1716
2     634
3      40
4      10
Name: baños, dtype: int64

## PRECIO

In [43]:
datos.head()

titulo  \
0   Alojamiento entero: piso. Anfitrión: Javier   
0                                           NaN   
0                                           NaN   
1  Alojamiento entero: piso. Anfitrión: Melissa   
1                                           NaN   

                                            all_info  \
0  [2 huéspedes ,  1 dormitorio ,  2 camas ,  1 b...   
0  [6 huéspedes ,  3 dormitorios ,  4 camas ,  2 ...   
0  [5 huéspedes ,  2 dormitorios ,  4 camas ,  1 ...   
1  [2 huéspedes ,  1 dormitorio ,  1 cama ,  1 baño]   
1  [5 huéspedes ,  3 dormitorios ,  3 camas ,  1 ...   

                                     características  \
0  Alojamiento entero\n(apartamento): será solo p...   
0  Alojamiento entero\n(apartamento): será solo p...   
0  Alojamiento entero\n(apartamento): será solo p...   
1  Alojamiento entero\n(apartamento): será solo p...   
1  Alojamiento entero\n(apartamento): será solo p...   

                                              precio  \
0  55€\n / noche\n55€ por noche\n4,90\n(415 evalu...   
0  99€\n / noche\n99€ por noche\n4,40\n(20 evalua...   
0  83€\n / noche\n83€ por noche\n4,52\n(31 evalua...   
1  60€\n / noche\n60€ por noche\n4,80\n(5 evaluac...   
1  50€\n / noche\n50€ por noche\n4,84\n(25 evalua...   

                                                usos  \
0  ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...   
0  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...   
0  2 noches en Valencia / València\n25 de mar. de...   
1  2 noches en Madrid\n19 de ago. de 2022 - 21 de...   
1  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...   

                                     nombre  ciudad  \
0  *Studio Centre-Live-In Atocha-WiFi,A/C *  Madrid   
0  *Studio Centre-Live-In Atocha-WiFi,A/C *  Madrid   
0  *Studio Centre-Live-In Atocha-WiFi,A/C *  Madrid   
1    PISO MODERNO EN PLENO CENTRO DE MADRID  Madrid   
1    PISO MODERNO EN PLENO CENTRO DE MADRID  Madrid   

                                                urls  huespedes  dormitorios  \
0  https://www.airbnb.es/rooms/20814468?adults=1&...          2            1   
0  https://www.airbnb.es/rooms/20814468?adults=1&...          6            3   
0  https://www.airbnb.es/rooms/20814468?adults=1&...          5            2   
1  https://www.airbnb.es/rooms/18565479?adults=1&...          2            1   
1  https://www.airbnb.es/rooms/18565479?adults=1&...          5            3   

   camas  baños  
0      2      1  
0      4      2  
0      4      1  
1      1      1  
1      3      1

### PRECIO

In [44]:
datos["precio"] = datos["precio"].apply(cf.splity_salto_linea)

In [45]:
datos[["precio_eur", "borra_1", "borra_2", "valoracion", "borra_3", "borra_4"]] = datos["precio"].apply(pd.Series)

In [46]:
datos["precio_eur"] = datos["precio_eur"].apply(cf.get_info)

In [47]:
datos["precio_eur"].unique()

array([ 55,  99,  83,  60,  50,  68,  49,  85, 106,  61, 130,  53, 129,
       110,  54,  98, 120,  89,  77,  47,  76,  17, 241, 100,  44,  42,
        69,  90,  95,  80,  70,  45, 190, 170,  81,  18, 220,  65, 269,
       115, 150,  41, 185,  88,  25,  94, 105,  64,  35, 230, 101,  29,
       209, 175,  43,  73, 133,  15,  21, 144, 145, 107, 159, 205, 121,
        22, 122,  36,  23,  59, 149, 135, 104, 114, 167,  63, 178,  71,
       154, 199, 140,  87,  48, 116,  82,  40,  57, 208, 148, 132,  39,
       183, 118,  46, 160,  75, 182,  96, 172, 200, 193, 169, 112, 211,
       236, 166, 206, 165, 108, 127, 152,  79, 253, 103, 113, 119, 171,
        38, 204, 155, 176,  86,  52, 197, 184, 250, 189,  72, 156,  67,
        30,  56, 181, 125,  51, 195, 235, 260,  20, 179, 138, 224, 173,
       229, 109, 191,  97,  84, 222, 212,  78,  27, 164, 128, 180, 161,
       174, 330,  28, 238, 124, 228,  34, 286, 141, 240, 242,  26, 218,
       232,  58, 142, 344, 117, 298, 248, 210,  66, 163, 215, 20

In [48]:
datos["precio_eur"].value_counts()

50     68
60     54
90     54
120    50
35     49
       ..
157     1
388     1
318     1
596     1
225     1
Name: precio_eur, Length: 258, dtype: int64

In [49]:
datos["precio_eur"] = datos["precio_eur"].replace(0, int(datos["precio_eur"].mean()))

In [50]:
datos["precio_eur"].unique()

array([ 55,  99,  83,  60,  50,  68,  49,  85, 106,  61, 130,  53, 129,
       110,  54,  98, 120,  89,  77,  47,  76,  17, 241, 100,  44,  42,
        69,  90,  95,  80,  70,  45, 190, 170,  81,  18, 220,  65, 269,
       115, 150,  41, 185,  88,  25,  94, 105,  64,  35, 230, 101,  29,
       209, 175,  43,  73, 133,  15,  21, 144, 145, 107, 159, 205, 121,
        22, 122,  36,  23,  59, 149, 135, 104, 114, 167,  63, 178,  71,
       154, 199, 140,  87,  48, 116,  82,  40,  57, 208, 148, 132,  39,
       183, 118,  46, 160,  75, 182,  96, 172, 200, 193, 169, 112, 211,
       236, 166, 206, 165, 108, 127, 152,  79, 253, 103, 113, 119, 171,
        38, 204, 155, 176,  86,  52, 197, 184, 250, 189,  72, 156,  67,
        30,  56, 181, 125,  51, 195, 235, 260,  20, 179, 138, 224, 173,
       229, 109, 191,  97,  84, 222, 212,  78,  27, 164, 128, 180, 161,
       174, 330,  28, 238, 124, 228,  34, 286, 141, 240, 242,  26, 218,
       232,  58, 142, 344, 117, 298, 248, 210,  66, 163, 215, 20

### VALORACIÓN

In [51]:
datos["valoracion"] = datos["valoracion"].str.replace(",", ".")

In [52]:
datos["valoracion"] = datos["valoracion"].apply(cf.get_float)

In [53]:
datos["valoracion"] = datos["valoracion"].replace(0, datos["valoracion"].mean())

In [54]:
datos["valoracion"].fillna(int(datos["valoracion"].mean()), inplace=True)

In [55]:
datos["valoracion"].unique()

array([4.9 , 4.4 , 4.52, 4.8 , 4.84, 3.73, 4.93, 4.45, 4.43, 4.95, 4.  ,
       3.33, 4.77, 4.63, 4.44, 4.76, 4.64, 4.56, 4.68, 4.47, 4.89, 4.49,
       4.69, 4.2 , 4.83, 4.74, 4.58, 4.85, 4.38, 4.48, 4.73, 4.72, 4.17,
       4.82, 4.78, 4.88, 4.42, 3.55, 4.7 , 4.81, 4.98, 3.9 , 4.67, 4.53,
       4.61, 4.5 , 4.14, 4.75, 4.86, 4.65, 3.87, 4.87, 4.91, 4.46, 4.55,
       4.6 , 3.44, 5.  , 4.39, 4.29, 4.79, 4.22, 4.62, 4.96, 4.97, 4.71,
       4.66, 4.25, 4.13, 4.07, 4.37, 4.57, 3.86, 4.51, 4.3 , 4.92, 3.93,
       4.35, 4.15, 4.34, 4.54, 4.23, 4.59, 4.18, 4.94, 4.19, 4.11, 3.67,
       4.36, 4.28, 3.5 , 3.92, 3.69, 4.41, 4.99, 4.12, 3.88, 4.26, 3.89,
       3.83, 4.05, 4.33, 4.32, 4.21, 4.27, 3.4 , 4.09, 4.24, 3.99, 3.91,
       4.31, 4.1 , 3.25])

## CARACTERÍSTICAS

In [56]:
datos["características"] = datos["características"].apply(cf.splity_salto_linea)

### ALOJAMIENTO

In [57]:
datos["alojamiento"] = datos["características"].apply(cf.carac_alojamiento)

In [58]:
datos['alojamiento'].fillna('Habitación privada', inplace=True)

In [59]:
datos["alojamiento"].unique()

array(['Alojamiento entero', 'Habitación privada'], dtype=object)

In [60]:
datos["alojamiento"].value_counts()

Alojamiento entero    1861
Habitación privada     539
Name: alojamiento, dtype: int64

### LIMPIEZA

In [61]:
datos["limpieza"] = datos["características"].apply(cf.carac_limpieza)

In [62]:
datos["limpieza"].fillna('No Limpieza avanzada', inplace=True)

In [63]:
datos.limpieza.unique()

array(['Limpieza avanzada', 'No Limpieza avanzada'], dtype=object)

In [64]:
datos["alojamiento"].value_counts()

Alojamiento entero    1861
Habitación privada     539
Name: alojamiento, dtype: int64

### LLEGADA AUTÓNOMA

In [65]:
datos["llegada_autonoma"] = datos["características"].apply(cf.carac_llegada)

In [66]:
datos["llegada_autonoma"].fillna('No Llegada autónoma', inplace=True)

In [67]:
datos["llegada_autonoma"].unique()

array(['No Llegada autónoma', 'Llegada autónoma'], dtype=object)

In [68]:
datos["llegada_autonoma"].value_counts()

No Llegada autónoma    1707
Llegada autónoma        693
Name: llegada_autonoma, dtype: int64

### UBICACIÓN FANTÁSTICA

In [69]:
datos["ubicacion_fantastica"] = datos["características"].apply(cf.carac_ubicacion)

In [70]:
datos["ubicacion_fantastica"].fillna('No ubicación_fantastica', inplace=True)

In [71]:
datos["ubicacion_fantastica"].unique()

array(['No ubicación_fantastica', 'Ubicación fantástica'], dtype=object)

In [72]:
datos["ubicacion_fantastica"].value_counts()

No ubicación_fantastica    1594
Ubicación fantástica        806
Name: ubicacion_fantastica, dtype: int64

## USOS

In [73]:
datos.sample()

titulo  \
279  Alojamiento entero: piso. Anfitrión: Mario   

                                         all_info  \
279  [3 huéspedes ,  Estudio ,  1 cama ,  1 baño]   

                                       características  \
279  [Alojamiento entero, (apartamento): será solo ...   

                                                precio  \
279  [60€,  / noche, 60€ por noche, 4,73, (263 eval...   

                                                  usos  \
279  ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...   

                                                nombre  ciudad  \
279  Acogedor Estudio Madrid Centro La Latina-Lavapiés  Madrid   

                                                  urls  huespedes  \
279  https://www.airbnb.es/rooms/19438429?adults=1&...          3   

     dormitorios  ...  precio_eur   borra_1        borra_2 valoracion  \
279            0  ...          60   / noche  60€ por noche       4.73   

                borra_3  borra_4         alojamiento           limpieza  \
279  (263 evaluaciones)      NaN  Alojamiento entero  Limpieza avanzada   

        llegada_autonoma     ubicacion_fantastica  
279  No Llegada autónoma  No ubicación_fantastica  

[1 rows x 22 columns]

In [74]:
datos["usos"] = datos["usos"].apply(cf.splity_salto_linea)

### COCINA

In [75]:
datos["cocina"] = datos["usos"].apply(cf.usos_cocina)

In [76]:
datos["cocina"].fillna('No cocina', inplace=True)

In [77]:
datos["cocina"].unique()

array(['Cocina', 'No cocina'], dtype=object)

In [78]:
datos["cocina"].value_counts()

Cocina       1865
No cocina     535
Name: cocina, dtype: int64

### WIFI

In [79]:
datos["wifi"] = datos["usos"].apply(cf.usos_wifi)

In [80]:
datos["wifi"].fillna('No Wifi', inplace=True)

In [81]:
datos["wifi"].unique()

array(['Wifi', 'No Wifi'], dtype=object)

In [82]:
datos["wifi"].value_counts()

Wifi       1968
No Wifi     432
Name: wifi, dtype: int64

### LAVADORA

In [83]:
datos["lavadora"] = datos["usos"].apply(cf.usos_lavadora)

In [84]:
datos["lavadora"].fillna('No lavadora', inplace=True)

In [85]:
datos["lavadora"].unique()

array(['No lavadora', 'Lavadora'], dtype=object)

In [86]:
datos["lavadora"].value_counts()

Lavadora       1687
No lavadora     713
Name: lavadora, dtype: int64

### AIRE ACONDICIONADO

In [87]:
datos["aire"] = datos["usos"].apply(cf.usos_aire)

In [88]:
datos["aire"].fillna('No Aire acondicionado', inplace=True)

In [89]:
datos["aire"].unique()

array(['Aire acondicionado', 'No Aire acondicionado'], dtype=object)

In [90]:
datos["aire"].value_counts()

Aire acondicionado       1637
No Aire acondicionado     763
Name: aire, dtype: int64

### SECADOR PELO

In [91]:
datos["secador"] = datos["usos"].apply(cf.usos_secador)

In [92]:
datos["secador"].fillna('No Secador de pelo', inplace=True)

In [93]:
datos["secador"].unique()

array(['Secador de pelo', 'No Secador de pelo'], dtype=object)

In [94]:
datos["secador"].value_counts()

Secador de pelo       1276
No Secador de pelo    1124
Name: secador, dtype: int64

### FRIGORÍFICO

In [95]:
datos["frigorifico"] = datos["usos"].apply(cf.usos_frigorifico)

In [96]:
datos["frigorifico"].fillna('No Frigorífico', inplace=True)

In [97]:
datos["frigorifico"].unique()

array(['No Frigorífico', 'Frigorífico'], dtype=object)

In [98]:
datos["frigorifico"].value_counts()

No Frigorífico    1807
Frigorífico        593
Name: frigorifico, dtype: int64

# 5. Guardo .csv limpio

In [99]:
datos.columns

Index(['titulo', 'all_info', 'características', 'precio', 'usos', 'nombre',
       'ciudad', 'urls', 'huespedes', 'dormitorios', 'camas', 'baños',
       'precio_eur', 'borra_1', 'borra_2', 'valoracion', 'borra_3', 'borra_4',
       'alojamiento', 'limpieza', 'llegada_autonoma', 'ubicacion_fantastica',
       'cocina', 'wifi', 'lavadora', 'aire', 'secador', 'frigorifico'],
      dtype='object')

In [100]:
df = datos[['huespedes', 'dormitorios', 'camas',
       'baños', 'precio_eur', 'valoracion',
       'alojamiento', 'limpieza', 'llegada_autonoma',
       'ubicacion_fantastica', 'wifi', 'cocina','lavadora', 'aire',
       'secador', 'frigorifico', 'ciudad', 'nombre', 'urls']]

In [101]:
df.isna().sum()

huespedes               0
dormitorios             0
camas                   0
baños                   0
precio_eur              0
valoracion              0
alojamiento             0
limpieza                0
llegada_autonoma        0
ubicacion_fantastica    0
wifi                    0
cocina                  0
lavadora                0
aire                    0
secador                 0
frigorifico             0
ciudad                  0
nombre                  0
urls                    0
dtype: int64

In [102]:
df.duplicated().sum()

0

In [103]:
df.to_csv("../data/datos_limpios_completos.csv", index=False)

In [104]:
df.drop_duplicates()

huespedes  dormitorios  camas  baños  precio_eur  valoracion  \
0             2            1      2      1          55        4.90   
0             6            3      4      2          99        4.40   
0             5            2      4      1          83        4.52   
1             2            1      1      1          60        4.80   
1             5            3      3      1          50        4.84   
...         ...          ...    ...    ...         ...         ...   
1195          4            1      2      1          75        4.50   
1196          2            1      1      1          51        4.86   
1197          4            0      1      1          59        4.50   
1198          2            0      1      1          70        4.65   
1199          3            1      2      1          55        4.80   

             alojamiento              limpieza     llegada_autonoma  \
0     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
0     Alojamiento entero  No Limpieza avanzada  No Llegada autónoma   
0     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
...                  ...                   ...                  ...   
1195  Alojamiento entero  No Limpieza avanzada  No Llegada autónoma   
1196  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1197  Alojamiento entero     Limpieza avanzada     Llegada autónoma   
1198  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1199  Alojamiento entero  No Limpieza avanzada  No Llegada autónoma   

         ubicacion_fantastica     wifi     cocina     lavadora  \
0     No ubicación_fantastica     Wifi     Cocina  No lavadora   
0        Ubicación fantástica     Wifi     Cocina     Lavadora   
0        Ubicación fantástica  No Wifi  No cocina  No lavadora   
1     No ubicación_fantastica  No Wifi  No cocina  No lavadora   
1     No ubicación_fantastica     Wifi     Cocina     Lavadora   
...                       ...      ...        ...          ...   
1195  No ubicación_fantastica     Wifi  No cocina  No lavadora   
1196  No ubicación_fantastica     Wifi  No cocina     Lavadora   
1197  No ubicación_fantastica     Wifi     Cocina     Lavadora   
1198     Ubicación fantástica     Wifi     Cocina     Lavadora   
1199     Ubicación fantástica     Wifi     Cocina     Lavadora   

                       aire             secador     frigorifico   ciudad  \
0        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid   
0        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid   
0     No Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid   
1     No Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid   
1        Aire acondicionado     Secador de pelo     Frigorífico   Madrid   
...                     ...                 ...             ...      ...   
1195     Aire acondicionado  No Secador de pelo     Frigorífico  Sevilla   
1196     Aire acondicionado     Secador de pelo  No Frigorífico  Sevilla   
1197     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla   
1198     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla   
1199     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla   

                                               nombre  \
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   
1              PISO MODERNO EN PLENO CENTRO DE MADRID   
1              PISO MODERNO EN PLENO CENTRO DE MADRID   
...                                               ...   
1195                               BELLA VISTA MODERN   
1196    Suite habitación doble (baño y salón privado)   
1197           Center, Studio with POOL in la Judería   
1198       Ático con Terraza junto a

# OUTLIERS

In [105]:
def gimme_the_otliers(s):
    Q1 = s.quantile(0.25)
    Q3 = s.quantile(0.75)
    IQR = Q3-Q1
    min_v = Q1 - (1.5 * IQR)
    max_v = Q3 + (1.5 * IQR)
    
    return [value for value in s if ((value < min_v) or (value>max_v))]

In [106]:
set(gimme_the_otliers(df.precio_eur))

{260,
 264,
 265,
 269,
 270,
 275,
 283,
 286,
 290,
 294,
 298,
 300,
 308,
 317,
 318,
 323,
 330,
 341,
 344,
 376,
 388,
 394,
 430,
 473,
 500,
 596}

In [107]:
set(gimme_the_otliers(df.camas))

{9}

In [108]:
set(gimme_the_otliers(df.baños))

{4}

In [109]:
df.to_csv("../data/datos_limpios_final_outliers.csv", index=False)

In [110]:
df_sin_outliers = df[(df["camas"] != 9 ) & (df["baños"] != 4 ) & (df["precio_eur"] < 250 )]

In [111]:
df_sin_outliers

huespedes  dormitorios  camas  baños  precio_eur  valoracion  \
0             2            1      2      1          55        4.90   
0             6            3      4      2          99        4.40   
0             5            2      4      1          83        4.52   
1             2            1      1      1          60        4.80   
1             5            3      3      1          50        4.84   
...         ...          ...    ...    ...         ...         ...   
1195          4            1      2      1          75        4.50   
1196          2            1      1      1          51        4.86   
1197          4            0      1      1          59        4.50   
1198          2            0      1      1          70        4.65   
1199          3            1      2      1          55        4.80   

             alojamiento              limpieza     llegada_autonoma  \
0     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
0     Alojamiento entero  No Limpieza avanzada  No Llegada autónoma   
0     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
...                  ...                   ...                  ...   
1195  Alojamiento entero  No Limpieza avanzada  No Llegada autónoma   
1196  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1197  Alojamiento entero     Limpieza avanzada     Llegada autónoma   
1198  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1199  Alojamiento entero  No Limpieza avanzada  No Llegada autónoma   

         ubicacion_fantastica     wifi     cocina     lavadora  \
0     No ubicación_fantastica     Wifi     Cocina  No lavadora   
0        Ubicación fantástica     Wifi     Cocina     Lavadora   
0        Ubicación fantástica  No Wifi  No cocina  No lavadora   
1     No ubicación_fantastica  No Wifi  No cocina  No lavadora   
1     No ubicación_fantastica     Wifi     Cocina     Lavadora   
...                       ...      ...        ...          ...   
1195  No ubicación_fantastica     Wifi  No cocina  No lavadora   
1196  No ubicación_fantastica     Wifi  No cocina     Lavadora   
1197  No ubicación_fantastica     Wifi     Cocina     Lavadora   
1198     Ubicación fantástica     Wifi     Cocina     Lavadora   
1199     Ubicación fantástica     Wifi     Cocina     Lavadora   

                       aire             secador     frigorifico   ciudad  \
0        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid   
0        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid   
0     No Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid   
1     No Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid   
1        Aire acondicionado     Secador de pelo     Frigorífico   Madrid   
...                     ...                 ...             ...      ...   
1195     Aire acondicionado  No Secador de pelo     Frigorífico  Sevilla   
1196     Aire acondicionado     Secador de pelo  No Frigorífico  Sevilla   
1197     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla   
1198     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla   
1199     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla   

                                               nombre  \
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   
0            *Studio Centre-Live-In Atocha-WiFi,A/C *   
1              PISO MODERNO EN PLENO CENTRO DE MADRID   
1              PISO MODERNO EN PLENO CENTRO DE MADRID   
...                                               ...   
1195                               BELLA VISTA MODERN   
1196    Suite habitación doble (baño y salón privado)   
1197           Center, Studio with POOL in la Judería   
1198       Ático con Terraza junto a

In [112]:
df_sin_outliers.to_csv("../data/datos_limpios_sin_outliers.csv", index=False)