# 1. Importo Librerías

In [1]:
import pandas as pd
import numpy as np
import re

# Importing the cleaning functions:
import sys
sys.path.append("../")
import src.cleaning_functions as cf

# 2. Cargo Datos

# 3. EDA

In [2]:
datos_1d = pd.read_csv("../data/datos_1_dorm.csv")

In [3]:
datos_4h = pd.read_csv("../data/datos_4_h_m_v_s.csv")

In [4]:
datos_ana = pd.read_csv("../data/datos_4_h_v_s.csv")

In [5]:
datos_4h_val = datos_ana[:300]

In [6]:
datos = pd.concat([datos_1d, datos_4h, datos_4h_val ], axis=0)

In [7]:
datos

titulo  \
0          Alojamiento entero: piso. Anfitrión: Javier   
1         Alojamiento entero: piso. Anfitrión: Melissa   
2          Alojamiento entero: piso. Anfitrión: Javier   
3    Alojamiento entero: piso. Anfitrión: Julio Víctor   
4    Alojamiento entero: piso. Anfitrión: Airbnbleg...   
..                                                 ...   
295                                                NaN   
296                                                NaN   
297                                                NaN   
298                                                NaN   
299                                                NaN   

                                              all_info  \
0        2 huéspedes · 1 dormitorio · 2 camas · 1 baño   
1         2 huéspedes · 1 dormitorio · 1 cama · 1 baño   
2        2 huéspedes · 1 dormitorio · 2 camas · 1 baño   
3       5 huéspedes · 2 dormitorios · 3 camas · 1 baño   
4        4 huéspedes · 1 dormitorio · 2 camas · 1 baño   
..                                                 ...   
295    8 huéspedes · 3 dormitorios · 4 camas · 2 baños   
296      5 huéspedes · 1 dormitorio · 3 camas · 1 baño   
297  7 huéspedes · 4 dormitorios · 7 camas · 1,5 baños   
298    5 huéspedes · 3 dormitorios · 6 camas · 2 baños   
299     6 huéspedes · 2 dormitorios · 3 camas · 1 baño   

                                       características  \
0    Alojamiento entero\n(apartamento): será solo p...   
1    Alojamiento entero\n(apartamento): será solo p...   
2    Alojamiento entero\n(apartamento): será solo p...   
3    Alojamiento entero\n(apartamento): será solo p...   
4    Alojamiento entero\n(apartamento): será solo p...   
..                                                 ...   
295  Alojamiento entero\n(apartamento): será solo p...   
296  Alojamiento entero\n(apartamento): será solo p...   
297  Alojamiento entero\n(apartamento): será solo p...   
298  Alojamiento entero\n(apartamento): será solo p...   
299  Alojamiento entero\n(apartamento): será solo p...   

                                                precio  \
0    55€\n / noche\n55€ por noche\n4,90\n(415 evalu...   
1    60€\n / noche\n60€ por noche\n4,80\n(5 evaluac...   
2    55€\n / noche\n55€ por noche\n4,93\n(46 evalua...   
3    85€\n / noche\n85€ por noche\n4,95\n(459 evalu...   
4    60€\n / noche\n60€ por noche\n3,33\n(3 evaluac...   
..                                                 ...   
295  228€\n / noche\n228€ por noche\n4,91\n(11 eval...   
296  93€\n / noche\n93€ por noche\n3,50\n(8 evaluac...   
297  160€\n / noche\n160€ por noche\n4,85\n(89 eval...   
298  125€\n / noche\n125€ por noche\n5,0\n(6 evalua...   
299  121€\n / noche\n121€ por noche\n4,69\n(26 eval...   

                                                  usos  
0    ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...  
1    2 noches en Madrid\n19 de ago. de 2022 - 21 de...  
2    ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...  
3    ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...  
4    ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...  
..                                                 ...  
295  ¿Dónde dormirás?\n1 de 2 páginas\n1 / 2\nDormi...  
296  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...  
297  2 noches en València\n1 de jul. de 2022 - 3 de...  
298  ¿Qué hay en este alojamiento?\nVistas al perfi...  
299  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...  

[2400 rows x 5 columns]

# 4. Limpieza Datos:

## ALL_INFO

In [8]:
datos["all_info"] = datos["all_info"].apply(cf.splity_info)

In [9]:
datos[["huespedes", "dormitorios", "camas", "baños"]] = datos["all_info"].apply(pd.Series)

### Huéspedes

In [10]:
datos["huespedes"].unique()

array(['2 huéspedes ', '5 huéspedes ', '4 huéspedes ', '1 huésped ',
       '3 huéspedes ', '6 huéspedes ', 'No hay dato', '10 huéspedes ',
       '7 huéspedes ', '8 huéspedes ', '9 huéspedes ', '12 huéspedes '],
      dtype=object)

In [11]:
datos["huespedes"] = datos["huespedes"].apply(cf.get_info)

In [12]:
datos["huespedes"].unique()

array([ 2,  5,  4,  1,  3,  6,  0, 10,  7,  8,  9, 12])

In [13]:
datos["huespedes"] = datos["huespedes"].replace(0, datos["huespedes"].mode()[0])

In [14]:
datos["huespedes"].unique()

array([ 2,  5,  4,  1,  3,  6, 10,  7,  8,  9, 12])

In [15]:
datos["huespedes"].value_counts()

6     666
2     593
5     417
4     252
1     154
3     113
8      97
7      85
10     12
9       9
12      2
Name: huespedes, dtype: int64

### Dormitorios

In [16]:
datos["dormitorios"] = datos["dormitorios"].apply(cf.get_info)

In [17]:
datos["dormitorios"].unique()

array([1, 2, 0, 3, 4, 5, 6])

In [18]:
datos["dormitorios"].value_counts()

1    938
2    718
3    531
0    140
4     66
5      6
6      1
Name: dormitorios, dtype: int64

### Camas

In [19]:
datos["camas"].unique()

array([' 2 camas ', ' 1 cama ', ' 3 camas ', ' 10 camas ',
       ' 1 baño compartido', ' 1 baño', ' 4 baños compartidos',
       ' 1,5 baños', ' 4 camas ', nan, ' 1,5 baños compartidos',
       ' 5 camas ', ' 6 camas ', ' 1 baño privado', ' 5 camas',
       ' 7 camas ', ' 8 camas ', ' 2,5 baños', ' 2 baños',
       ' 2 baños compartidos', ' 3 baños', ' 3 camas', ' 11 camas ',
       ' 9 camas '], dtype=object)

In [20]:
datos["camas"] = datos["camas"].apply(cf.info_camas)

In [21]:
datos["camas"].fillna(int(datos["camas"].mode()), inplace=True)

In [22]:
datos["camas"] = datos["camas"].apply(cf.get_integrer)

In [23]:
datos["camas"].unique()

array([2, 1, 3, 4, 5, 6, 7, 8, 9])

In [24]:
datos["camas"].value_counts()

1    753
3    451
4    440
2    416
5    202
6     90
7     36
8      7
9      5
Name: camas, dtype: int64

### Baños

In [25]:
datos["baños"].unique()

array([' 1 baño', ' 1,5 baños', ' 1 baño compartido', ' 2 baños',
       ' 4 baños compartidos', ' 1 baño privado', ' 3 baños compartidos',
       nan, ' 2 baños compartidos', ' 1,5 baños compartidos', ' 3 baños',
       ' 0 baños compartidos', ' 2,5 baños compartidos', ' 2,5 baños',
       ' 4 baños', ' 4,5 baños', ' 3,5 baños'], dtype=object)

In [26]:
datos["baños"] = datos["baños"].apply(cf.info_baños)

In [27]:
datos["baños"].fillna(int(datos["baños"].mode()), inplace=True)

In [28]:
datos["baños"] = datos["baños"].apply(cf.get_integrer)

In [29]:
datos["baños"] = datos["baños"].replace(0, datos["baños"].mode()[0])

In [30]:
datos["baños"].unique()

array([1, 2, 4, 3])

In [31]:
datos["baños"].value_counts()

1    1716
2     634
3      40
4      10
Name: baños, dtype: int64

## PRECIO

In [32]:
datos.head()

titulo  \
0        Alojamiento entero: piso. Anfitrión: Javier   
1       Alojamiento entero: piso. Anfitrión: Melissa   
2        Alojamiento entero: piso. Anfitrión: Javier   
3  Alojamiento entero: piso. Anfitrión: Julio Víctor   
4  Alojamiento entero: piso. Anfitrión: Airbnbleg...   

                                            all_info  \
0  [2 huéspedes ,  1 dormitorio ,  2 camas ,  1 b...   
1  [2 huéspedes ,  1 dormitorio ,  1 cama ,  1 baño]   
2  [2 huéspedes ,  1 dormitorio ,  2 camas ,  1 b...   
3  [5 huéspedes ,  2 dormitorios ,  3 camas ,  1 ...   
4  [4 huéspedes ,  1 dormitorio ,  2 camas ,  1 b...   

                                     características  \
0  Alojamiento entero\n(apartamento): será solo p...   
1  Alojamiento entero\n(apartamento): será solo p...   
2  Alojamiento entero\n(apartamento): será solo p...   
3  Alojamiento entero\n(apartamento): será solo p...   
4  Alojamiento entero\n(apartamento): será solo p...   

                                              precio  \
0  55€\n / noche\n55€ por noche\n4,90\n(415 evalu...   
1  60€\n / noche\n60€ por noche\n4,80\n(5 evaluac...   
2  55€\n / noche\n55€ por noche\n4,93\n(46 evalua...   
3  85€\n / noche\n85€ por noche\n4,95\n(459 evalu...   
4  60€\n / noche\n60€ por noche\n3,33\n(3 evaluac...   

                                                usos  huespedes  dormitorios  \
0  ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...          2            1   
1  2 noches en Madrid\n19 de ago. de 2022 - 21 de...          2            1   
2  ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...          2            1   
3  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...          5            2   
4  ¿Qué hay en este alojamiento?\nCocina\nWifi\nT...          4            1   

   camas  baños  
0      2      1  
1      1      1  
2      2      1  
3      3      1  
4      2      1

### PRECIO

In [33]:
datos["precio"] = datos["precio"].apply(cf.splity_salto_linea)

In [34]:
datos[["precio_eur", "borra_1", "borra_2", "valoracion", "borra_3", "borra_4"]] = datos["precio"].apply(pd.Series)

In [35]:
datos["precio_eur"] = datos["precio_eur"].apply(cf.get_info)

In [36]:
datos["precio_eur"].unique()

array([ 55,  60,  85,  54,  47,  17,  44,  42,  50,  45,  18,  65,  70,
        41,  25,  35,  29,  43,  15,  21,  22,  36,  23,  59,  63,  71,
        69,  48,  40,  57,  49,  39,  46,  75,  68,  38,  52,  64,  80,
        67,  30,  56,  89,  51,  20,  94,  72,  53,  90,  82,  27,  84,
        28,  34,  61,  26,  58,  66,  19,  31,  37, 125,  62,   0,  93,
        79, 100,  10,  32,  33,  16,  86, 120,  95, 107,  77,  24,  83,
       104,  99, 124, 160,  97, 163, 130,  96, 143, 108, 127,  87, 112,
       103, 109, 116, 134, 190, 175, 122, 182, 106, 198, 140, 207, 113,
       139, 110,  98,  11,  92,  12, 180,  88,  81,  73, 123,  13,  76,
       153, 199, 102,  78,  14, 114,  74, 115, 165, 129, 241, 170, 220,
       269, 150, 185, 230, 209, 144, 145, 159, 205, 149, 135, 178, 133,
       208, 148, 132, 183, 200, 193, 169, 211, 236, 206, 152, 172, 167,
       119, 204, 155, 176, 184, 250, 189, 181, 195, 260, 179, 173, 229,
       191, 212, 164, 174, 238, 228, 161, 171, 218, 232, 344, 29

In [37]:
datos["precio_eur"].value_counts()

50     68
90     54
60     54
120    50
35     49
       ..
203     1
216     1
233     1
202     1
430     1
Name: precio_eur, Length: 258, dtype: int64

In [38]:
datos["precio_eur"] = datos["precio_eur"].replace(0, int(datos["precio_eur"].mean()))

In [39]:
datos["precio_eur"].unique()

array([ 55,  60,  85,  54,  47,  17,  44,  42,  50,  45,  18,  65,  70,
        41,  25,  35,  29,  43,  15,  21,  22,  36,  23,  59,  63,  71,
        69,  48,  40,  57,  49,  39,  46,  75,  68,  38,  52,  64,  80,
        67,  30,  56,  89,  51,  20,  94,  72,  53,  90,  82,  27,  84,
        28,  34,  61,  26,  58,  66,  19,  31,  37, 125,  62,  98,  93,
        79, 100,  10,  32,  33,  16,  86, 120,  95, 107,  77,  24,  83,
       104,  99, 124, 160,  97, 163, 130,  96, 143, 108, 127,  87, 112,
       103, 109, 116, 134, 190, 175, 122, 182, 106, 198, 140, 207, 113,
       139, 110,  11,  92,  12, 180,  88,  81,  73, 123,  13,  76, 153,
       199, 102,  78,  14, 114,  74, 115, 165, 129, 241, 170, 220, 269,
       150, 185, 230, 209, 144, 145, 159, 205, 149, 135, 178, 133, 208,
       148, 132, 183, 200, 193, 169, 211, 236, 206, 152, 172, 167, 119,
       204, 155, 176, 184, 250, 189, 181, 195, 260, 179, 173, 229, 191,
       212, 164, 174, 238, 228, 161, 171, 218, 232, 344, 298, 24

### VALORACIÓN

In [40]:
datos["valoracion"] = datos["valoracion"].str.replace(",", ".")

In [41]:
datos["valoracion"] = datos["valoracion"].apply(cf.get_float)

In [42]:
datos["valoracion"] = datos["valoracion"].replace(0, datos["valoracion"].mean())

In [43]:
datos["valoracion"].fillna(int(datos["valoracion"].mean()), inplace=True)

In [44]:
datos["valoracion"].unique()

array([4.9 , 4.8 , 4.93, 4.95, 3.33, 4.44, 4.56, 4.89, 4.2 , 4.83, 4.  ,
       4.58, 4.85, 4.72, 4.82, 4.42, 4.76, 4.61, 4.64, 4.75, 4.86, 3.87,
       4.84, 4.55, 3.44, 5.  , 4.43, 4.78, 4.79, 4.67, 4.68, 4.81, 4.6 ,
       4.91, 4.96, 4.97, 4.71, 4.48, 4.29, 3.86, 4.66, 4.88, 4.73, 3.93,
       4.35, 4.15, 4.7 , 4.65, 4.57, 4.34, 4.54, 4.63, 4.59, 4.18, 4.4 ,
       4.49, 4.45, 4.52, 4.37, 4.94, 4.62, 4.69, 4.39, 4.92, 4.36, 4.47,
       4.77, 4.87, 3.69, 4.99, 4.12, 4.14, 4.28, 4.11, 3.88, 4.53, 4.74,
       4.38, 4.26, 4.33, 4.5 , 4.51, 4.32, 4.22, 4.27, 4.25, 4.07, 4.3 ,
       3.9 , 4.24, 4.19, 4.46, 3.99, 4.98, 4.21, 4.13, 4.31, 4.41, 4.23,
       4.1 , 4.17, 3.55, 3.73, 3.67, 3.92, 3.83, 3.4 , 4.09, 3.91, 3.25,
       3.5 , 3.89, 4.05])

## CARACTERÍSTICAS

In [45]:
datos["características"] = datos["características"].apply(cf.splity_salto_linea)

### ALOJAMIENTO

In [46]:
datos["alojamiento"] = datos["características"].apply(cf.carac_alojamiento)

In [47]:
datos['alojamiento'].fillna('Habitación privada', inplace=True)

In [48]:
datos["alojamiento"].unique()

array(['Alojamiento entero', 'Habitación privada'], dtype=object)

In [49]:
datos["alojamiento"].value_counts()

Alojamiento entero    1861
Habitación privada     539
Name: alojamiento, dtype: int64

### LIMPIEZA

In [50]:
datos["limpieza"] = datos["características"].apply(cf.carac_limpieza)

In [51]:
datos["limpieza"].fillna('No Limpieza avanzada', inplace=True)

In [52]:
datos.limpieza.unique()

array(['Limpieza avanzada', 'No Limpieza avanzada'], dtype=object)

In [53]:
datos["alojamiento"].value_counts()

Alojamiento entero    1861
Habitación privada     539
Name: alojamiento, dtype: int64

### LLEGADA AUTÓNOMA

In [54]:
datos["llegada_autonoma"] = datos["características"].apply(cf.carac_llegada)

In [55]:
datos["llegada_autonoma"].fillna('No Llegada autónoma', inplace=True)

In [56]:
datos["llegada_autonoma"].unique()

array(['No Llegada autónoma', 'Llegada autónoma'], dtype=object)

In [57]:
datos["llegada_autonoma"].value_counts()

No Llegada autónoma    1707
Llegada autónoma        693
Name: llegada_autonoma, dtype: int64

### UBICACIÓN FANTÁSTICA

In [58]:
datos["ubicacion_fantastica"] = datos["características"].apply(cf.carac_ubicacion)

In [59]:
datos["ubicacion_fantastica"].fillna('No ubicación_fantastica', inplace=True)

In [60]:
datos["ubicacion_fantastica"].unique()

array(['No ubicación_fantastica', 'Ubicación fantástica'], dtype=object)

In [61]:
datos["ubicacion_fantastica"].value_counts()

No ubicación_fantastica    1594
Ubicación fantástica        806
Name: ubicacion_fantastica, dtype: int64

## USOS

In [62]:
datos.sample()

titulo  \
881  Alojamiento entero: loft. Anfitrión: Lidia Y Q...   

                                              all_info  \
881  [4 huéspedes ,  1 dormitorio ,  2 camas ,  1 b...   

                                       características  \
881  [Alojamiento entero, (loft): será solo para ti...   

                                                precio  \
881  [76€,  / noche, 76€ por noche, 4,93, (161 eval...   

                                                  usos  huespedes  \
881  ¿Qué hay en este alojamiento?\nCocina\nWifi\nA...          4   

     dormitorios  camas  baños  precio_eur   borra_1        borra_2  \
881            1      2      1          76   / noche  76€ por noche   

     valoracion             borra_3 borra_4         alojamiento  \
881        4.93  (161 evaluaciones)     NaN  Alojamiento entero   

              limpieza     llegada_autonoma  ubicacion_fantastica  
881  Limpieza avanzada  No Llegada autónoma  Ubicación fantástica

In [63]:
datos["usos"] = datos["usos"].apply(cf.splity_salto_linea)

### COCINA

In [64]:
datos["cocina"] = datos["usos"].apply(cf.usos_cocina)

In [65]:
datos["cocina"].fillna('No cocina', inplace=True)

In [66]:
datos["cocina"].unique()

array(['Cocina', 'No cocina'], dtype=object)

In [67]:
datos["cocina"].value_counts()

Cocina       1865
No cocina     535
Name: cocina, dtype: int64

### WIFI

In [68]:
datos["wifi"] = datos["usos"].apply(cf.usos_wifi)

In [69]:
datos["wifi"].fillna('No Wifi', inplace=True)

In [70]:
datos["wifi"].unique()

array(['Wifi', 'No Wifi'], dtype=object)

In [71]:
datos["wifi"].value_counts()

Wifi       1968
No Wifi     432
Name: wifi, dtype: int64

### LAVADORA

In [72]:
datos["lavadora"] = datos["usos"].apply(cf.usos_lavadora)

In [73]:
datos["lavadora"].fillna('No lavadora', inplace=True)

In [74]:
datos["lavadora"].unique()

array(['No lavadora', 'Lavadora'], dtype=object)

In [75]:
datos["lavadora"].value_counts()

Lavadora       1687
No lavadora     713
Name: lavadora, dtype: int64

### AIRE ACONDICIONADO

In [76]:
datos["aire"] = datos["usos"].apply(cf.usos_aire)

In [77]:
datos["aire"].fillna('No Aire acondicionado', inplace=True)

In [78]:
datos["aire"].unique()

array(['Aire acondicionado', 'No Aire acondicionado'], dtype=object)

In [79]:
datos["aire"].value_counts()

Aire acondicionado       1637
No Aire acondicionado     763
Name: aire, dtype: int64

### SECADOR PELO

In [80]:
datos["secador"] = datos["usos"].apply(cf.usos_secador)

In [81]:
datos["secador"].fillna('No Secador de pelo', inplace=True)

In [82]:
datos["secador"].unique()

array(['Secador de pelo', 'No Secador de pelo'], dtype=object)

In [83]:
datos["secador"].value_counts()

Secador de pelo       1276
No Secador de pelo    1124
Name: secador, dtype: int64

### FRIGORÍFICO

In [84]:
datos["frigorifico"] = datos["usos"].apply(cf.usos_frigorifico)

In [85]:
datos["frigorifico"].fillna('No Frigorífico', inplace=True)

In [86]:
datos["frigorifico"].unique()

array(['No Frigorífico', 'Frigorífico'], dtype=object)

In [87]:
datos["frigorifico"].value_counts()

No Frigorífico    1807
Frigorífico        593
Name: frigorifico, dtype: int64

# 5. Guardo .csv limpio

In [88]:
datos.columns

Index(['titulo', 'all_info', 'características', 'precio', 'usos', 'huespedes',
       'dormitorios', 'camas', 'baños', 'precio_eur', 'borra_1', 'borra_2',
       'valoracion', 'borra_3', 'borra_4', 'alojamiento', 'limpieza',
       'llegada_autonoma', 'ubicacion_fantastica', 'cocina', 'wifi',
       'lavadora', 'aire', 'secador', 'frigorifico'],
      dtype='object')

In [89]:
df = datos[['huespedes', 'dormitorios', 'camas',
       'baños', 'precio_eur', 'valoracion',
       'alojamiento', 'limpieza', 'llegada_autonoma',
       'ubicacion_fantastica', 'wifi', 'cocina','lavadora', 'aire',
       'secador', 'frigorifico']]

In [90]:
df.isna().sum()

huespedes               0
dormitorios             0
camas                   0
baños                   0
precio_eur              0
valoracion              0
alojamiento             0
limpieza                0
llegada_autonoma        0
ubicacion_fantastica    0
wifi                    0
cocina                  0
lavadora                0
aire                    0
secador                 0
frigorifico             0
dtype: int64

In [91]:
df.duplicated().sum()

362

In [92]:
df.to_csv("../data/datos_limpios.csv", index=False)

In [93]:
df_ = pd.read_csv("../data/final.csv")

In [94]:
df_.drop_duplicates()

huespedes  dormitorios  camas  baños  precio_eur  valoracion  \
0             2            1      2      1          55        4.90   
1             2            1      1      1          60        4.80   
2             2            1      2      1          55        4.93   
3             5            2      3      1          85        4.95   
4             4            1      2      1          60        3.33   
...         ...          ...    ...    ...         ...         ...   
2395          8            3      4      2         228        4.91   
2396          5            1      3      1          93        3.50   
2397          7            4      7      1         160        4.85   
2398          5            3      6      2         125        5.00   
2399          6            2      3      1         121        4.69   

             alojamiento              limpieza     llegada_autonoma  \
0     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
3     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
4     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
...                  ...                   ...                  ...   
2395  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2396  Alojamiento entero  No Limpieza avanzada     Llegada autónoma   
2397  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2398  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2399  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   

         ubicacion_fantastica     wifi     cocina     lavadora  \
0     No ubicación_fantastica     Wifi     Cocina  No lavadora   
1     No ubicación_fantastica  No Wifi  No cocina  No lavadora   
2        Ubicación fantástica     Wifi     Cocina  No lavadora   
3        Ubicación fantástica     Wifi     Cocina     Lavadora   
4        Ubicación fantástica     Wifi     Cocina  No lavadora   
...                       ...      ...        ...          ...   
2395  No ubicación_fantastica  No Wifi  No cocina  No lavadora   
2396  No ubicación_fantastica     Wifi     Cocina     Lavadora   
2397  No ubicación_fantastica  No Wifi  No cocina  No lavadora   
2398  No ubicación_fantastica     Wifi     Cocina     Lavadora   
2399  No ubicación_fantastica     Wifi     Cocina     Lavadora   

                       aire             secador     frigorifico   ciudad  
0        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid  
1     No Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid  
2        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid  
3        Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid  
4     No Aire acondicionado  No Secador de pelo     Frigorífico   Madrid  
...                     ...                 ...             ...      ...  
2395  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2396  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2397  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2398  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2399     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  

[2045 rows x 17 columns]

# OUTLIERS

In [101]:
def gimme_the_otliers(s):
    Q1 = s.quantile(0.25)
    Q3 = s.quantile(0.75)
    IQR = Q3-Q1
    min_v = Q1 - (1.5 * IQR)
    max_v = Q3 + (1.5 * IQR)
    
    return [value for value in s if ((value < min_v) or (value>max_v))]

In [103]:
set(gimme_the_otliers(df_.precio_eur))

{260,
 264,
 265,
 269,
 270,
 275,
 283,
 286,
 290,
 294,
 298,
 300,
 308,
 317,
 318,
 323,
 330,
 341,
 344,
 376,
 388,
 394,
 430,
 473,
 500,
 596}

In [106]:
set(gimme_the_otliers(df_.camas))

{9}

In [108]:
set(gimme_the_otliers(df_.baños))

{4}

In [109]:
df_.to_csv("../data/datos_limpios_final_outliers.csv", index=False)

In [114]:
df_sin_outliers = df_[(df_["camas"] != 9 ) & (df_["baños"] != 4 ) & (df_["precio_eur"] < 250 )]

In [115]:
df_sin_outliers

huespedes  dormitorios  camas  baños  precio_eur  valoracion  \
0             2            1      2      1          55        4.90   
1             2            1      1      1          60        4.80   
2             2            1      2      1          55        4.93   
3             5            2      3      1          85        4.95   
4             4            1      2      1          60        3.33   
...         ...          ...    ...    ...         ...         ...   
2395          8            3      4      2         228        4.91   
2396          5            1      3      1          93        3.50   
2397          7            4      7      1         160        4.85   
2398          5            3      6      2         125        5.00   
2399          6            2      3      1         121        4.69   

             alojamiento              limpieza     llegada_autonoma  \
0     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
1     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
3     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
4     Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
...                  ...                   ...                  ...   
2395  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2396  Alojamiento entero  No Limpieza avanzada     Llegada autónoma   
2397  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2398  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   
2399  Alojamiento entero     Limpieza avanzada  No Llegada autónoma   

         ubicacion_fantastica     wifi     cocina     lavadora  \
0     No ubicación_fantastica     Wifi     Cocina  No lavadora   
1     No ubicación_fantastica  No Wifi  No cocina  No lavadora   
2        Ubicación fantástica     Wifi     Cocina  No lavadora   
3        Ubicación fantástica     Wifi     Cocina     Lavadora   
4        Ubicación fantástica     Wifi     Cocina  No lavadora   
...                       ...      ...        ...          ...   
2395  No ubicación_fantastica  No Wifi  No cocina  No lavadora   
2396  No ubicación_fantastica     Wifi     Cocina     Lavadora   
2397  No ubicación_fantastica  No Wifi  No cocina  No lavadora   
2398  No ubicación_fantastica     Wifi     Cocina     Lavadora   
2399  No ubicación_fantastica     Wifi     Cocina     Lavadora   

                       aire             secador     frigorifico   ciudad  
0        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid  
1     No Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid  
2        Aire acondicionado     Secador de pelo  No Frigorífico   Madrid  
3        Aire acondicionado  No Secador de pelo  No Frigorífico   Madrid  
4     No Aire acondicionado  No Secador de pelo     Frigorífico   Madrid  
...                     ...                 ...             ...      ...  
2395  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2396  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2397  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2398  No Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  
2399     Aire acondicionado  No Secador de pelo  No Frigorífico  Sevilla  

[2337 rows x 17 columns]

In [119]:
df_sin_outliers.to_csv("../data/datos_limpios_sin_outliers.csv", index=False)